---
name: ansible-lint

on:
  push: # All branches and tags
  # schedule:
  #   # Runs automatically on the 27th of every month at 04:30 UTC
  #   - cron: "30 04 27 * *"

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
